services:
  - type: web
    name: enchant-forex-api
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm run server
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_ORIGIN
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: MONGO_URI
        sync: false


